### PR TITLE
Tl42 144 fe search bar atom component 리팩토링

### PR DESCRIPTION
**Pull request by Lee-Byung-Kyu**
https://user-images.githubusercontent.com/69182505/183826737-ba2f3e43-31ab-48fd-8c3d-89a18e8b2173.mov
Uploading Screen Recording 2022-08-10 at 3.01.57 PM.mov…

Special thanks to JangBalJang...

### CODE REVIEW

**Comment by Lee-Byung-Kyu** [comment]
https://user-images.githubusercontent.com/69182505/183827011-95afaac7-3474-4ad6-a2d8-090485d3c7d4.mov

https://user-images.githubusercontent.com/69182505/183827032-a88f1729-84dc-482b-bdc9-e327f41de1b2.mov

**Comment by Lee-Byung-Kyu** [comment]
Special thanks to JangBalJang

**Review by T2SU — APPROVED** [review]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by JihoonNoahLee** [comment]
React Hook을 학습하는 좋은 계기가 되었길 바래요~

**Pull request merged**
